name: Test Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-test-with-jest:
    runs-on: ubuntu-latest

    steps:
      # checkout the repository content
      - name: Checkout
        uses: actions/checkout@v4

      # setup nodejs environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      # change to backend directory
      - name: Change to backend directory
        run: cd backend

      # install dependencies
      - name: Install dependencies
        run: npm install

      # run tests
      - name: Run Jest tests
        run: npm test
